spring:
  database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  version: '1.16.4'
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
jwt:
  token:
    secret-key: MySubProject Modong`s jwt secret-key
    access:
      expire-time: 86400
    refresh:
      expire-time: 604800

allow-cors:
  list: http://localhost

swagger:
  api-server-url: http://localhost:8080
  description: 로컬 테스트용 서버