spring:
  database-platform: org.hibernate.dialect.H2Dialect
  mvc: # Swagger
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  token:
    secret-key: MySubProject Modong`s jwt secret-key
    access:
      expire-time: 86400
    refresh:
      expire-time: 604800

allow-cors:
  list: http://localhost