name: Deploy to Amazon EC2 modong prod api server

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## gradle clean
      - name: Clean project with Gradle
        run: ./gradlew clean

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      ## gradle test
      - name: Test with Gradle
        run: ./gradlew --info test
